on:
  workflow_call:
    inputs:
      base_sha:
        required: true
        type: string
    outputs:
      general:
        value: "${{ jobs.analyse-services.outputs.general }}"
      service1:
        value: "${{ jobs.analyse-services.outputs.service1 }}"
      service2:
        value: "${{ jobs.analyse-services.outputs.service2 }}"
      tests:
        value: "${{ jobs.analyse-services.outputs.tests }}"    
jobs:
  analyse-services:
    name: analyse-services
    runs-on: [ubuntu-latest]
    outputs:
      general: "${{ steps.changes-general.outputs.any_changed }}"
      service1: "${{ steps.changes-service1.outputs.any_changed }}"
      service2: "${{ steps.changes-service2.outputs.any_changed }}"
      tests: "${{ steps.changes-tests.outputs.any_changed }}"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: general
        id: changes-general
        uses: tj-actions/changed-files@v33
        with:
          base_sha: ${{ inputs.base_sha }}
          files: |
            .github/**
            services/**
            common/**
            data-layer/**
            scripts/generate-config/**
            package.json
            package-lock.json

      - name: service1
        id: changes-service1
        uses: tj-actions/changed-files@v33
        with:
          base_sha: ${{ inputs.base_sha }}
          files: |
            .github/**
            services/service1/**
            common/**
            data-layer/**
            scripts/generate-config/**
            package.json
            package-lock.json

      - name: service2
        id: changes-service2
        uses: tj-actions/changed-files@v33
        with:
          base_sha: ${{ inputs.base_sha }}
          files: |
            .github/**
            services/service2/**
            common/**
            data-layer/**
            scripts/generate-config/**
            package.json
            package-lock.json

      - name: tests
        id: changes-tests
        uses: tj-actions/changed-files@v33
        with:
          base_sha: ${{ inputs.base_sha }}
          files: |
            .github/**
            tests/**
            docs/client-api/**
            docs/dashboard-api/**

      # Example 1
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v33

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done