on:
  workflow_call:
    inputs:
      base_sha:
        required: true
        type: string
    outputs:
      service1:
        value: "${{ jobs.analyse-services.outputs.service1 }}"
      service2:
        value: "${{ jobs.analyse-services.outputs.service2 }}"
        
jobs:
  analyse-services:
    name: analyse-services
    runs-on: [ubuntu-latest]
    outputs:
      service1: "${{ steps.changes-service1.outputs.any_changed }}"
      service2: "${{ steps.changes-service2.outputs.any_changed }}"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: service1
        id: changes-service1
        uses: tj-actions/changed-files@v33
        with:
          base_sha: ${{ inputs.base_sha }}
          files: |
            .github/**
            services/service1/**
            common/**
            package.json

      - name: service2
        id: changes-service2
        uses: tj-actions/changed-files@v33
        with:
          base_sha: ${{ inputs.base_sha }}
          files: |
            .github/**
            services/service2/**
            common/**
            package.json