on:
  workflow_call:
    inputs:
      base_sha:
        type: string
        required: true

jobs:
  analyse-services:
    uses: ./.github/workflows/analyse-services.yml
    with:
      base_sha: ${{inputs.base_sha}}
      
  service1:
    name: service1
    needs: analyse-services
    if: "${{ needs.analyse-services.outputs.service1 == 'true' }}"
    runs-on: ubuntu-latest
    steps:
      - name: run step
        run: echo "deploying service1"

  service2:
    name: service2
    needs: analyse-services
    if: "${{ needs.analyse-services.outputs.service2 == 'true' }}"
    runs-on: ubuntu-latest
    steps:
      - name: run step
        run: echo "deploying service2"