name: feature ci/cd-workflow
on:
  push:
    branches:
      - feature/*

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      base_sha: ${{ github.event.push.base.sha }}